# Generated by Django 5.1.2 on 2024-12-13 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_student_m21_alter_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='M21',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course'),
        ),
    ]
